/**
 * The app's own icons, as a GResource compiled into this module.
 *
 * GENERATED by `scripts/build-icon-resource.mjs` — do not edit. Run that script
 * after changing anything in `app/src/frontends/gui/resources/`.
 *
 * It is base64 in a TypeScript file rather than a `.gresource` next to the bundle
 * because the bundle is the artefact: one file, nothing beside it to install,
 * nothing to lose. `icons.ts` registers it with the icon theme at startup.
 */

/** Where `Gtk.IconTheme` must look to find them. */
export const ICON_RESOURCE_PREFIX = '/eu/jumplink/Troedler/icons';

/**
 * SHA-256 of the SVG this was compiled from.
 *
 * Carried so `scripts/guard-icon-names.mjs` can check the resource against its
 * source on a machine that has no `glib-compile-resources` — which is every CI
 * runner that is not this workstation.
 */
export const ICON_SOURCE_SHA256 = '406f2cdb39af441202a503a4cb4e5d586cb961949383fd61b78fafb6981c4e76';

/** The compiled resource, base64. 1576 bytes before encoding. */
export const ICON_RESOURCE_BASE64 =
  'R1ZhcmlhbnQAAAAAAAAAABgAAADIAAAAAAAAKAYAAAAAAAAAAAAAAAIAAAAEAAAABAAAAAYAAAA9knh8AwAAAMgAAAADAEwAzAAA' +
  'ANAAAACRLrcXBQAAANAAAAAGAEwA2AAAANwAAAAychGFAQAAANwAAAAcAHYA+AAAAAEGAADUtQIA/////wEGAAABAEwABAYAAAgG' +
  'AADW7AkKAAAAAAgGAAAJAEwAFAYAABgGAAAmhVZEBAAAABgGAAAJAEwAJAYAACgGAABldS8ABAAAAGljb25zLwAAAgAAAHRyb2Vk' +
  'bGVyLWZpbHRlci1zeW1ib2xpYy5zdmf5BAAAAAAAADw/eG1sIHZlcnNpb249IjEuMCIgZW5jb2Rpbmc9IlVURi04Ij8+CjwhLS0K' +
  'ICBBIGZ1bm5lbCwgZHJhd24gZm9yIHRoaXMgYXBwLiAxNsOXMTYsIG9uZSBmaWxsZWQgcGF0aCwgdGhlIHN5bWJvbGljIHN0eWxl' +
  'IHRoZQogIEdOT01FIEhJRyBzcGVjaWZpZXMgZm9yIFVJIGljb25zOiBhIHNpbmdsZSBwcm9wZXJ0eSAobmFycm93aW5nIGEgbGlz' +
  'dCksCiAgYWxpZ25lZCB0byB0aGUgcGl4ZWwgZ3JpZCwgYW5kIGl0IG11c3QgcmVhZCB0aGUgc2FtZSB3YXkgaW52ZXJ0ZWQg4oCU' +
  'IHdoaWNoIGlzCiAgd2h5IGl0IGlzIGEgc2lsaG91ZXR0ZSBhbmQgbm90IGFuIG91dGxpbmUuCgogIEl0IGlzIGFuIE9SSUdJTkFM' +
  'IHBhdGgsIG5vdCBhIGNvcHkuIFRoZSBHTk9NRSBJY29uIERldiBLaXQncyBgZmlsdGVyLXN5bWJvbGljYAogIGlzIHRoZSBvYnZp' +
  'b3VzIHNvdXJjZSBhbmQgdGhlIG9uZSB0aGlzIGZpbGUgd291bGQgY3JlZGl0IGlmIGl0IHdlcmUgcmVhY2hhYmxlOgogIHRoZSBs' +
  'aWJyYXJ5J3MgcmF3IFVSTCBhbnN3ZXJzIDQwNCBmcm9tIGhlcmUgYW5kIHRoZSBkZXYga2l0IGlzIG5vdCBpbnN0YWxsZWQgb24K' +
  'ICB0aGlzIG1hY2hpbmUsIHNvIHRoZSBob25lc3Qgb3B0aW9ucyB3ZXJlIHRvIGRyYXcgb25lIG9yIHRvIHB1dCBhIHdyb25nIGlj' +
  'b24gb24KICB0aGUgYnV0dG9uIChgcHJlZmVyZW5jZXMtb3RoZXItc3ltYm9saWNgIGlzIGEgcGVyc29uIHdpdGggYSB3cmVuY2gs' +
  'CiAgYHZpZXctc29ydC1kZXNjZW5kaW5nLXN5bWJvbGljYCBpcyBhIHNvcnQgZ2x5cGgsIG5laXRoZXIgaXMgYSBmaWx0ZXIpLiBE' +
  'cmF3bgogIGZyb20gdGhlIEhJRydzIHJ1bGVzIGluc3RlYWQg4oCUIGh0dHBzOi8vZGV2ZWxvcGVyLmdub21lLm9yZy9oaWcvZ3Vp' +
  'ZGVsaW5lcy91aS1pY29ucy5odG1sCgogIENvbG91cnM6IGAjMjIyMjIyYCBpcyB0aGUgZmlsbCBHTk9NRSdzIHN5bWJvbGljIFNW' +
  'R3Mgc2hpcCB3aXRoLiBHVEsgcmVjb2xvdXJzCiAgYSBgLXN5bWJvbGljYCBpY29uIHdoZW4gaXQgbG9hZHMgaXQsIHNvIHRoaXMg' +
  'ZXhhY3QgdmFsdWUgbmV2ZXIgcmVhY2hlcyB0aGUKICBzY3JlZW47IGl0IGlzIHdoYXQgdGhlIFNWRyBoYXMgdG8gYmUgKmRyYXdu' +
  'KiBpbi4KLS0+CjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIHZp' +
  'ZXdCb3g9IjAgMCAxNiAxNiI+CiAgPHBhdGggZmlsbD0iIzIyMjIyMiIgZD0iTSAxLDIgTCAxNSwyIEwgOSw5LjUgTCA5LDEzLjUg' +
  'TCA3LDEzLjUgTCA3LDkuNSBaIi8+Cjwvc3ZnPgoAACh1dWF5KS8AAAAAAABqdW1wbGluay8AAAAFAAAAVHJvZWRsZXIvAAAAAQAA' +
  'AA==';
