/**
 * The app's own icons, registered with the icon theme.
 *
 * One icon, one reason: the filter button asked for `view-filter-symbolic` and
 * the Adwaita theme has no such name. That is not a graceful degradation — a
 * missing `-symbolic` name on a `Gtk.MenuButton` renders as an empty white
 * rectangle, so the control that opens the filters looked broken rather than
 * present. Every GNOME app that needs a funnel bundles one, so this bundles one.
 *
 * The resource is base64 inside the bundle rather than a file beside it
 * (`icon-resource.ts` is generated by `scripts/build-icon-resource.mjs`): the
 * bundle is the artefact, and a second file is a second thing to install and a
 * second thing to lose silently.
 *
 * `scripts/guard-icon-names.mjs` is the other half: it fails the build if any
 * icon name the GUI uses stops resolving — here, or in the Adwaita theme.
 */

import Gdk from '@girs/gdk-4.0';
import Gio from '@girs/gio-2.0';
import GLib from '@girs/glib-2.0';
import Gtk from '@girs/gtk-4.0';

import { ICON_RESOURCE_BASE64, ICON_RESOURCE_PREFIX } from './icon-resource.ts';

/** The name the filter button asks for, resolved out of the resource above. */
export const FILTER_ICON = 'troedler-filter-symbolic';

let registered = false;

/**
 * Put the resource in front of the icon theme.
 *
 * Called from `MainWindow`, not from `main.ts`: `Gtk.IconTheme.get_for_display`
 * needs a display, and there is none until the application is being started. It
 * is idempotent because that is the only thing a caller can check — the theme
 * instance belongs to GTK, and registering the same resource twice would make
 * every lookup walk two copies of one icon.
 */
export function registerIcons(): void {
  if (registered) return;
  const display = Gdk.Display.get_default();
  // A window cannot be built without a display, so this is unreachable in
  // practice; it is here because the type says it can be null, and shipping a
  // white rectangle because a null check was missing would be a poor
  // advertisement for a guard.
  if (!display) return;
  const bytes = Uint8Array.from(atob(ICON_RESOURCE_BASE64), (c) => c.charCodeAt(0));
  Gio.resources_register(Gio.Resource.new_from_data(new GLib.Bytes(bytes)));
  Gtk.IconTheme.get_for_display(display).add_resource_path(ICON_RESOURCE_PREFIX);
  registered = true;
}
