/**
 * `explainUrl` — the action behind `troedler robots`.
 *
 * These run against the REAL registry rather than stub providers, because the
 * whole defect was a surface that answered from its own idea of the program.
 * A test built on a hand-made provider list would reproduce that mistake one
 * level down: it would prove the printer consistent with a fiction.
 *
 * The discriminator throughout is the fake fetch's call log. What this command
 * must get right is not only its verdict but WHICH REQUESTS IT MAKES — a
 * verification command that contacts a switched-off host to prove it is never
 * contacted is its own defect.
 */

import { describe, expect, it } from '@gjsify/unit';

import { HttpClient, RateLimiter } from '@troedler/http';
import type { TroedlerConfig } from '@troedler/store';

import { explainUrl } from '../../../src/core/actions/robots.ts';
import { buildProviders } from '../../../src/core/registry.ts';
import type { Context } from '../../../src/core/context.ts';

/** The wildcard group `api.booklooker.de` really serves — measured 2026-08-22, 68 344 bytes. */
const BOOKLOOKER_ROBOTS = `# do not edit - this file is generated by daily update
User-agent: Googlebot
User-agent: Bingbot

Disallow: /interface/
Disallow: /app/priv/

User-agent: *

Disallow: /
`;

const QUOKA_ROBOTS = `User-agent: *
Allow: /
Disallow: /Suchergebnis/
`;

interface Rig {
  readonly context: Context;
  readonly calls: string[];
}

function rig(config: Partial<TroedlerConfig> = {}): Rig {
  const calls: string[] = [];
  const fetchImpl = (async (input: string | URL | Request) => {
    const url = typeof input === 'string' ? input : input instanceof URL ? input.toString() : input.url;
    calls.push(url);
    const parsed = new URL(url);
    if (parsed.pathname !== '/robots.txt') return new Response('nope', { status: 404 });
    if (parsed.host === 'api.booklooker.de') return new Response(BOOKLOOKER_ROBOTS, { status: 200 });
    if (parsed.host === 'www.quoka.de') return new Response(QUOKA_ROBOTS, { status: 200 });
    return new Response('', { status: 404 });
  }) as typeof fetch;

  const http = new HttpClient({
    version: '0.0.0-test',
    limiter: new RateLimiter({ sleep: async () => {} }),
    fetchImpl,
  });
  const full: TroedlerConfig = { version: 1, providers: {}, defaults: {}, ...config } as TroedlerConfig;
  const providers = buildProviders({ http, env: {}, config: full });

  return {
    calls,
    context: {
      config: full,
      configPath: '/dev/null',
      http,
      providers,
      store: () => {
        throw new Error('kein Store in diesem Test');
      },
      closeStore: () => {},
    } as unknown as Context,
  };
}

export default async () => {
  await describe('explainUrl: die dokumentierte API', async () => {
    await it('erlaubt die Booklooker-API, die deren robots.txt verbietet', async () => {
      // The measurement this whole action exists for. On 2026-08-22 the built
      // bundle answered:
      //   VERBOTEN: https://api.booklooker.de/2.0/search?token=x&titel=y
      //     robots.txt von api.booklooker.de verbietet … (Disallow: /).
      // for the URL every Booklooker search fetches under a free API key.
      const { context, calls } = rig();
      const v = await explainUrl(context, 'https://api.booklooker.de/2.0/search?token=x&titel=y');

      expect(v.allowed).toBe(true);
      expect(v.basis).toBe('licence');
      expect(v.provider?.id).toBe('booklooker');
      expect(v.provider?.access).toBe('official-api');
      // No politeness floor, because there is none in the run either.
      expect(v.delaySeconds).toBe(0);
      // The discriminator: the file that WOULD have refused is never fetched.
      // Without this the test passes on an implementation that downloads 68 KB
      // per invocation and then ignores it.
      expect(calls).toHaveLength(0);
      expect(v.robots).toBe(null);
      expect(v.robotsSkipped?.includes('Lizenz')).toBe(true);
      expect(v.source?.doc).toBe('docs/quellen/booklooker.de.md');
    });

    await it('nennt die Quelle und die Akte, statt sie raten zu lassen', async () => {
      const { context } = rig();
      const v = await explainUrl(context, 'https://api.ebay.com/buy/browse/v1/item_summary/search?q=x');
      expect(v.provider?.label).toBe('eBay');
      expect(v.basis).toBe('licence');
      // The old command printed "(dieser Host liefert keine robots.txt)" here —
      // a statement about a file the run never requests.
      expect(v.robots).toBe(null);
    });
  });

  await describe('explainUrl: was wirklich passiert', async () => {
    await it('lehnt eine abgeschaltete Quelle ab, ohne ihren Host anzufassen', async () => {
      // kleinanzeigen.de is off by default because its terms forbid automated
      // access. The old command hard-coded `enabled: true`, printed "erlaubt"
      // for a source that is never fetched — and fetched its robots.txt to say
      // so. A request for robots.txt is still a request.
      const { context, calls } = rig();
      const v = await explainUrl(context, 'https://www.kleinanzeigen.de/s-fahrrad/k0');

      expect(v.allowed).toBe(false);
      expect(v.reason).toBe('disabled');
      expect(v.basis).toBe('disabled');
      expect(v.provider?.enabled).toBe(false);
      expect(calls).toHaveLength(0);
      expect(v.detail?.includes('Nutzungsbedingungen')).toBe(true);
    });

    await it('liest robots.txt für eine eingeschaltete HTML-Quelle und nennt die Regel', async () => {
      const { context, calls } = rig();
      const allowed = await explainUrl(context, 'https://www.quoka.de/anzeigen/?q=fahrrad');
      expect(allowed.allowed).toBe(true);
      expect(allowed.basis).toBe('robots');
      expect(allowed.delaySeconds).toBe(2);
      expect(allowed.robots).toBe('parsed');
      expect(calls).toEqualArray(['https://www.quoka.de/robots.txt']);

      const refused = await explainUrl(context, 'https://www.quoka.de/Suchergebnis/rad');
      expect(refused.allowed).toBe(false);
      expect(refused.reason).toBe('robots');
      expect(refused.detail?.includes('Disallow: /Suchergebnis/')).toBe(true);
    });

    await it('sagt, dass ein fremder Host hypothetisch ist', async () => {
      // No adapter reaches this host, so any verdict about it describes a
      // request troedler will never make. Printing "erlaubt" alone implied one.
      const { context } = rig();
      const v = await explainUrl(context, 'https://www.example.invalid/x');
      expect(v.provider).toBe(null);
      expect(v.source).toBe(null);
      expect(v.robots).toBe('absent');
    });

    await it('fragt robots.txt über das Schema der URL ab', async () => {
      // `robotsStateFor` took a bare host and always probed https, so
      // `troedler robots http://…` answered out of a different file than the
      // one that would govern.
      const { context, calls } = rig();
      await explainUrl(context, 'http://www.example.invalid/x');
      expect(calls).toEqualArray(['http://www.example.invalid/robots.txt']);
    });

    await it('verweigert eine URL, die keine ist, mit einem lesbaren Satz', async () => {
      const { context } = rig();
      let message = '';
      try {
        await explainUrl(context, 'www.quoka.de/anzeigen');
      } catch (err) {
        message = err instanceof Error ? err.message : String(err);
      }
      expect(message.includes('keine vollständige URL')).toBe(true);
    });
  });
};
